FROM node:20-alpine as build
WORKDIR /app
COPY frontend .
RUN npm install -g @angular/cli && npm install && ng build --configuration production

FROM nginx:alpine
COPY --from=build /app/dist/frontend/browser/ /usr/share/nginx/html/
COPY nginx/default.conf /etc/nginx/conf.d/default.conf
